name: Automated tests 

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target 
        required: true
        default: all_tests
        type: choice 
        options:
          - all_tests

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test: 
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Chrome
      run: sudo apt-get install google-chrome-stable

    - name: install dependencies
      run: pip install -r requirements.txt

    # artefacts

    - name: all_tests
      if: "github.event.inputs.deployment_target == 'all_tests'"
      run: pytest -v tests/test_example.py --alluredir allure-results
      continue-on-error: true
        
    
          
      
